#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset

python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --no-input
# python /app/manage.py collectstatic --noinput
gunicorn core.wsgi --bind 0.0.0.0:9000 --chdir=/app
# python /app/manage.py runserver 0.0.0.0:9000
