# Generated by Django 3.0.9 on 2020-08-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='cases/')),
                ('description', models.TextField(blank=True, max_length=128, null=True)),
                ('goal', models.CharField(max_length=64)),
                ('solution', models.CharField(max_length=128)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('presentation', models.FileField(blank=True, null=True, upload_to='presentations/', verbose_name='Presentation file')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CasePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cases_casepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
