# Generated by Django 3.0.9 on 2020-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='duration',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
