#!/bin/sh

set -o errexit
set -o nounset

command npm init -y
command npm i --save node-fetch

postgres_ready() {
node << END
const fetch = require("node-fetch");
const url = "http://cms:1337/cases";

const getData = async url => {
    try {
        const response = await fetch(url);
        const json = await response.json();
        process.exit(0)
    } catch (error) {
        console.log(error);
        process.exit(-1)
    }
};

getData(url);

END
}
until postgres_ready; do
  >&2 echo 'Waiting for CMS to become available...'
  sleep 5
done
>&2 echo 'CMS is available'

exec "$@"