#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset



python /telegram/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput
gunicorn --debug core.wsgi --bind 0.0.0.0:5000 --chdir=/telegram

